# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07f6eae24fa106d6d06a092997c7ae1f2c5e973b4693cc0e4ef12e3a891fcabf8825bdcab9dd88002585ef0e921947b2f1559d350946ed0a5826d39f5fd76062

test:
  secret_key_base: c2d1060315abb685736d2c23eeb8e02e95e3ff3fc655cf60e83c5ceeb3180c76c62c8f036b73d15cf9648a22ddeefed2c557c11400e9b48d4f8bb69e50313c8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
